name: CI Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Lint_Build_Test:
    name: Linting and testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositary
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Build Code
        run: npm run build --if-present

      - name: Test Code
        run: npm run test
